name: CD (Android)

on:
  push:
    branches:
    - appcenter
    - appcenter-android

jobs:
  android-build:
    runs-on: windows-latest
    
    steps:
    - name: Install AppCenter CLI Tools
      run: npm install -g appcenter-cli

    - name: Trigger AppCenter Build
      env:
        AppCenterAppSlug: ${{ secrets.APPCENTER_ANDROID_APP_SLUG }}
        AppCenterApiToken: ${{ secrets.APPCENTER_API_TOKEN }}
        BranchToTrigger: ${{ env:github.ref }}
      run: |
        # $filePath = "src\DevReach2020\DevReach2020.Forms\Android\Properties\AndroidManifest.xml"
        # [xml]$XML = Get-Content -Path $filePath
        # $buildNum = $XML.manifest.versionCode
        # $buildName = $XML.manifest.versionName
        
        appcenter build queue --app $env:AppCenterAppSlug --branch $BranchToTrigger --token $AppCenterApiToken
