name: CD (Android)

on:
  push:
    branches:
    - release-android
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'

jobs:
  android-build:
    runs-on: windows-latest
    steps:
    # AppCenter release to Google Play production
    - name: AppCenter Build and Release
      run: |
        npm install -g appcenter-cli
        appcenter build queue --app "lance-mccarthy-1uw5/devreach-2020-android" --branch "release-android" --token ${{ secrets.APPCENTER_API_TOKEN }}
