name: Xamarin.Forms

on:
  push:
    branches:
    - main

jobs:
  windows-build:
    runs-on: windows-latest
    env:
      Configuration: Debug
      Signing_Certificate: LancelotSoftwareLLC.pfx
      Telerik_Username: ${{ secrets.TELERIK_USERNAME }}
      Telerik_Password: ${{ secrets.TELERIK_PASSWORD }}
      NuGetConfig_Path: src\DevReach2020\nuget.config
      Project_Directory: src\DevReach2020\DevReach2020.Forms\UWP
      Project_Path: src\DevReach2020\DevReach2020.Forms\UWP\DevReach2020.Forms.UWP.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.302

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.1

    - name: NuGet Restore
      run: dotnet restore $env:Project_Path --configfile $env:NuGetConfig_Path --runtime $env:RID
      env:
        RID: win-x86 # https://docs.microsoft.com/en-us/dotnet/core/rid-catalog

    - name: Decode the pfx
      run: |
        $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.Base64_Encoded_Pfx }}")
        $certificatePath = Join-Path -Path $env:Project_Directory -ChildPath $env:Signing_Certificate
        [IO.File]::WriteAllBytes("$certificatePath", $pfx_cert_byte)

    - name: Build UWP Project
      run: msbuild $env:Project_Path /p:Configuration=$env:Configuration /p:UapAppxPackageBuildMode=$env:Appx_Package_Build_Mode /p:AppxBundle=$env:Appx_Bundle /p:PackageCertificateKeyFile=$env:Signing_Certificate /p:PackageCertificatePassword=${{ secrets.Pfx_Key }}
      env:
        Appx_Bundle: Always
        Appx_Bundle_Platforms: x86
        Appx_Package_Build_Mode: StoreUpload

    - name: Remove the pfx
      run: Remove-Item -path $env:Project_Directory\$env:Signing_Certificate

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: UWP Artifacts
        path: ${{ env.Project_Directory }}\AppPackages

  android-build:
    runs-on: windows-latest
    env:
      Configuration: Debug
      Signing_Certificate: LancelotSoftwareLLC.pfx
      Telerik_Username: ${{ secrets.TELERIK_USERNAME }}
      Telerik_Password: ${{ secrets.TELERIK_PASSWORD }}
      NuGetConfig_Path: src\DevReach2020\nuget.config
      Project_Directory: src\DevReach2020\DevReach2020.Forms\Android
      Project_Path: src\DevReach2020\DevReach2020.Forms\Android\DevReach2020.Forms.Android.csproj
      
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  
    
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.302  
    
    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.1
    
    - name: NuGet Restore
      run: dotnet restore $env:Project_Path --configfile $env:NuGetConfig_Path --runtime $env:RID
      env:
        RID: any # https://docs.microsoft.com/en-us/dotnet/core/rid-catalog 
    
    - name: Build Android Project
      run: msbuild $env:Project_Path /p:Configuration=$env:Configuration /p:Platform="any cpu"

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Android Artifacts
        path: ${{ env.Project_Directory }}\bin\Debug

  ios-build:
    runs-on: macos-latest
    env:
      Configuration: Debug
      Telerik_Username: ${{ secrets.TELERIK_USERNAME }}
      Telerik_Password: ${{ secrets.TELERIK_PASSWORD }}
      NuGetConfig_Path: src\DevReach2020\nuget.config
      Project_Directory: src\DevReach2020\DevReach2020.Forms\iOS
      iOS_Project_Path: src\DevReach2020\DevReach2020.Forms\iOS\DevReach2020.Forms.iOS.csproj 

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  
    
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.302  
    
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.1
    
    - name: NuGet Restore
      run: dotnet restore $env:Project_Path --configfile $env:NuGetConfig_Path --runtime $env:RID
      env:
        RID: any # https://docs.microsoft.com/en-us/dotnet/core/rid-catalog 
    
    - name: Build iOS Project
      run: msbuild $env:Project_Path /p:Configuration=$env:Configuration /p:Platform="iPhoneSimulator"

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Android Artifacts
        path: ${{ env.Project_Directory }}\bin\iPhoneSimulator\Debug
